id: IC4A88880
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:29:26+00:00'
last_modified: '2022-06-08T10:05:20.954052+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3997
  title: གྲུབ་མཐའི་རྣམ་བཞག་མདོར་བསྡུས་ནོར་བུའི་འཕྲེང་བ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AAD5:
      image_group_id: I1KG4064
      title: ''
      total_pages: 64
      order: 1
      base_file: AAD5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
