id: IC4A88880
legacy_id: P009307
ocr_import_info:
  bdrc_scan_id: W1KG3997
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T11:28:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:21:23.339819+00:00'
last_modified: 2022-08-31 23:21:28.553702
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3997
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3997
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་མཐའི་རྣམ་བཞག་མདོར་བསྡུས་ནོར་བུའི་འཕྲེང་བ།
  author: འཇམ་དབྱངས་བཞད་པ ༠༢་དཀོན་མཆོག་འཇིགས་མེད་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.5352402685332618
  ocr_word_median_confidence_index: 0.5
quality: null
bases:
  I1KG4064:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4064
      total_pages: 64
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4064.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5352402685332618
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
